// JS reference implementation of the account logic. The production server is Rust
// (crates/wkdash-core); this double only backs the in-page fake server of the browser e2e.
//
// KEEP IN SYNC WITH THE RUST CODE. tests/fixtures/golden-state.json is generated by the Rust
// tests (UPDATE_GOLDEN=1 cargo nextest run) and tests/fake-server.test.js asserts this double
// produces the identical /api/state for the same scenario, so drift fails the browser suite.

import { WkApi, AuthError } from '../../public/js/api.js';
import { sync, seed, validateSeed } from './sync.js';
import { KEYED, EVENTS, json } from './tables.js';

export const THROTTLE_MS = 60_000;
export const POLL_MS = 15 * 60_000;

export class Account {
  /**
   * @param {{store: object, base: string, getFetch: (scenario?: string) => Promise<typeof fetch>,
   *          arm: () => Promise<void>, disarm: () => Promise<void>, destroy: () => Promise<void>, throttleMs?: number}} deps
   */
  constructor(deps) {
    this.d = deps;
    this.store = deps.store;
    this.throttleMs = deps.throttleMs ?? THROTTLE_MS;
    this.now = deps.now ?? (() => new Date());
    this.running = null;
    this.scenario = undefined;
  }

  /** Route an /api request already authenticated by the Worker. */
  async handle(request, { user, token, scenario }) {
    if (scenario) this.scenario = scenario;
    const url = new URL(request.url);
    const path = url.pathname.replace(/^\/api/, '');
    const m = request.method;
    try {
      if (m === 'DELETE' && path === '/account') return json(await this.destroy());
      await this.ensureToken(token, user);
      if (m === 'GET' && path === '/state') return json(await this.state(Number(url.searchParams.get('since') ?? 0)));
      if (m === 'POST' && path === '/sync') return json(await this.runSync({ throttle: true, now: this.now() }));
      if (m === 'POST' && path === '/seed') {
        const body = await request.json().catch(() => null);
        const err = validateSeed(body);
        if (err) return json({ error: `Invalid seed: ${err}` }, 400);
        return this.seed(body);
      }
      return json({ error: 'Not found' }, 404);
    } catch (e) {
      if (e instanceof AuthError) return json({ error: 'WaniKani rejected the token' }, 401);
      console.error(e);
      return json({ error: e.message || String(e) }, 502);
    }
  }

  /** Remember the token we poll with; a new token for the same account (rotation) just replaces it. */
  async ensureToken(token, user) {
    if ((await this.store.getMeta('token')) !== token) await this.store.setMeta('token', token);
    if (!(await this.store.getMeta('user'))) await this.store.setMeta('user', user);
    if ((await this.store.getMeta('status')) === 'auth_failed') {
      await this.store.setMeta('status', 'active');
      await this.d.arm();
    }
  }

  async account() {
    return {
      status: (await this.store.getMeta('status')) ?? 'empty',
      user: await this.store.getMeta('user'),
      history_since: await this.store.getMeta('history_since'),
      last_sync: await this.store.getMeta('last_sync'),
      version: (await this.store.getMeta('version')) ?? 0,
    };
  }

  async state(since) {
    const account = await this.account();
    if (!Number.isFinite(since) || since < 0 || since > account.version) since = 0; // a recreated account restarts numbering
    const out = { account, since };
    for (const t of [...Object.keys(KEYED), ...EVENTS]) out[t] = account.status === 'empty' ? [] : await this.store.since(t, since);
    return out;
  }

  async api() {
    const token = await this.store.getMeta('token');
    return new WkApi(token, { fetch: await this.d.getFetch(this.scenario), base: this.d.base });
  }

  /** Sync now. Serialised: a concurrent call awaits the run in flight. */
  async runSync({ throttle = false, now = new Date() } = {}) {
    if (this.running) return this.running;
    const version = (await this.store.getMeta('version')) ?? 0;
    const last = await this.store.getMeta('last_sync');
    if (throttle && last && now.getTime() - Date.parse(last) < this.throttleMs) return { ran: false, version };
    this.running = (async () => {
      try {
        const r = await sync(await this.api(), this.store, { now });
        return { ran: true, ...r };
      } catch (e) {
        if (e instanceof AuthError) { await this.store.setMeta('status', 'auth_failed'); await this.d.disarm(); }
        throw e;
      } finally {
        this.running = null;
        if ((await this.store.getMeta('status')) === 'active') await this.d.arm();
      }
    })();
    return this.running;
  }

  async seed(body) {
    if ((await this.store.getMeta('status')) !== 'empty' && (await this.store.getMeta('status')) !== undefined) return json({ error: 'Account already has data' }, 409);
    const r = await seed(this.store, body);
    await this.d.arm();
    return json({ ok: true, ...r });
  }

  async destroy() {
    await this.d.disarm();
    await this.d.destroy();
    return { ok: true };
  }
}
